"""Module 7 — Annotated Notebook Generator.

Generates a Jupyter notebook (.ipynb) with 5 phases:
  Ph1: Dataset Prep
  Ph2: Model Init
  Ph3: Training Config (with confidence annotations + citations)
  Ph4: Training Loop
  Ph5: Evaluation
"""

from __future__ import annotations

import json
from datetime import datetime, timezone
from pathlib import Path


# ── Known dataset mappings for auto-fetch ──────────────────────────────
KNOWN_DATASETS = {
    "conll": ("conll2003", "ner_tags", "tokens"),
    "conll2003": ("conll2003", "ner_tags", "tokens"),
    "conll-2003": ("conll2003", "ner_tags", "tokens"),
    "squad": ("rajpurkar/squad", "answers", "question"),
    "squad2": ("rajpurkar/squad_v2", "answers", "question"),
    "imdb": ("imdb", "label", "text"),
    "sst": ("stanfordnlp/sst2", "label", "sentence"),
    "sst2": ("stanfordnlp/sst2", "label", "sentence"),
    "sst-2": ("stanfordnlp/sst2", "label", "sentence"),
    "mnli": ("nli", "label", "premise"),
    "mrpc": ("glue", "label", "sentence1"),
    "cola": ("glue", "label", "sentence"),
    "qqp": ("glue", "label", "question1"),
    "rte": ("glue", "label", "sentence1"),
    "wnli": ("glue", "label", "sentence1"),
    "qnli": ("glue", "label", "question"),
    "ag_news": ("ag_news", "label", "text"),
    "yelp": ("yelp_review_full", "label", "text"),
    "wikitext": ("wikitext", None, "text"),
    "trec": ("trec", "coarse_label", "text"),
    "snli": ("snli", "label", "premise"),
    "emotion": ("emotion", "label", "text"),
    "tweet_eval": ("tweet_eval", "label", "text"),
}


def _resolve_dataset(dataset_name: str) -> tuple:
    """Resolve a dataset name to (hf_id, label_col, text_col) or None."""
    if not dataset_name:
        return None
    key = dataset_name.lower().strip().replace(" ", "_").replace("-", "_")
    # Try exact match
    if key in KNOWN_DATASETS:
        return KNOWN_DATASETS[key]
    # Try partial match
    for known_key, value in KNOWN_DATASETS.items():
        if known_key in key or key in known_key:
            return value
    return None


def generate_notebook(
    validated_config: dict,
    evidence_report: dict,
    user_hp_json: dict,
    contradiction_report: dict | None = None,
    validation_result: dict | None = None,
    output_path: str = "notebook.ipynb",
) -> str:
    """Generate an annotated Jupyter notebook.

    Returns the path to the generated notebook.
    """
    cells = []

    # Extract flat config values
    config_vals = {}
    for param, entry in validated_config.items():
        if isinstance(entry, dict):
            config_vals[param] = entry.get("value")
        else:
            config_vals[param] = entry

    model_name = user_hp_json.get("model") or "bert-base-uncased"
    task = user_hp_json.get("task") or "text_classification"
    dataset_name = user_hp_json.get("dataset") or "custom_dataset"
    strategy = evidence_report.get("strategy", "unknown")
    n_evidence = evidence_report.get("total_evidence_papers", 0)

    # Resolve dataset to HuggingFace ID
    resolved_ds = _resolve_dataset(dataset_name)

    # ===================== Header =====================
    ds_badge = ""
    if resolved_ds:
        ds_badge = f"**Dataset Auto-Fetch**: ✅ `{resolved_ds[0]}` (HuggingFace)  \n"
    else:
        ds_badge = f"**Dataset**: ⚠️ `{dataset_name}` (manual setup required)  \n"

    cells.append(_md_cell(
        f"# 🔬 HyperBERT: Inferred Training Configuration\n\n"
        f"**Model**: `{model_name}`  \n"
        f"**Task**: `{task}`  \n"
        f"{ds_badge}"
        f"**Generated**: {datetime.now().strftime('%Y-%m-%d %H:%M')}  \n"
        f"**Evidence**: {n_evidence} similar papers (Strategy: {strategy})  \n\n"
        f"---\n\n"
        f"> This notebook was auto-generated by the HyperBERT system. "
        f"Each hyperparameter is annotated with its confidence level and source."
    ))

    # ===================== Config Summary =====================
    cells.append(_md_cell(_build_config_table(validated_config)))

    # Warnings section
    warnings_md = _build_warnings(contradiction_report, validation_result)
    if warnings_md:
        cells.append(_md_cell(warnings_md))

    # ===================== Ph1: Dataset Prep =====================
    cells.append(_md_cell("## Phase 1: Dataset Preparation"))

    if resolved_ds:
        hf_id, label_col, text_col = resolved_ds
        # Smart auto-loading code
        cells.append(_code_cell(
            f'# Phase 1: Dataset Preparation (Auto-Fetched)\n'
            f'from transformers import AutoTokenizer\n'
            f'from datasets import load_dataset\n\n'
            f'MODEL_NAME = "{model_name}"\n'
            f'MAX_SEQ_LENGTH = {config_vals.get("max_seq_length", 128)}\n\n'
            f'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n\n'
            f'# Auto-fetch dataset from HuggingFace\n'
            f'dataset = load_dataset("{hf_id}")\n'
            f'print(f"Dataset loaded: {hf_id}")\n'
            f'print(f"Train samples: {{len(dataset[\'train\'])}}")\n'
            f'print(f"Columns: {{dataset[\'train\'].column_names}}")\n\n'
            f'def tokenize_function(examples):\n'
            f'    return tokenizer(\n'
            f'        examples["{text_col}"],\n'
            f'        padding="max_length",\n'
            f'        truncation=True,\n'
            f'        max_length=MAX_SEQ_LENGTH,\n'
            f'    )\n\n'
            f'tokenized = dataset.map(tokenize_function, batched=True)\n'
            f'print(f"Tokenizer loaded: {{MODEL_NAME}}")\n'
            f'print(f"Max sequence length: {{MAX_SEQ_LENGTH}}")'
        ))
    else:
        cells.append(_code_cell(
            f'# Phase 1: Dataset Preparation\n'
            f'from transformers import AutoTokenizer\n'
            f'from datasets import load_dataset\n\n'
            f'MODEL_NAME = "{model_name}"\n'
            f'MAX_SEQ_LENGTH = {config_vals.get("max_seq_length", 128)}\n\n'
            f'tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)\n\n'
            f'# Load your dataset\n'
            f'# dataset = load_dataset("{dataset_name}")\n'
            f'# For custom datasets:\n'
            f'# dataset = load_dataset("csv", data_files={{"train": "train.csv", "test": "test.csv"}})\n\n'
            f'def tokenize_function(examples):\n'
            f'    return tokenizer(\n'
            f'        examples["text"],\n'
            f'        padding="max_length",\n'
            f'        truncation=True,\n'
            f'        max_length=MAX_SEQ_LENGTH,\n'
            f'    )\n\n'
            f'# tokenized = dataset.map(tokenize_function, batched=True)\n'
            f'print(f"Tokenizer loaded: {{MODEL_NAME}}")\n'
            f'print(f"Max sequence length: {{MAX_SEQ_LENGTH}}")'
        ))

    # ===================== Ph2: Model Init =====================
    cells.append(_md_cell("## Phase 2: Model Initialization"))
    cells.append(_code_cell(
        f'# Phase 2: Model Initialization\n'
        f'from transformers import AutoModelForSequenceClassification\n\n'
        f'NUM_LABELS = 2  # Adjust for your task\n\n'
        f'model = AutoModelForSequenceClassification.from_pretrained(\n'
        f'    MODEL_NAME,\n'
        f'    num_labels=NUM_LABELS,\n'
        f')\n\n'
        f'# Model parameters\n'
        f'total_params = sum(p.numel() for p in model.parameters())\n'
        f'trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)\n'
        f'print(f"Total parameters: {{total_params:,}}")\n'
        f'print(f"Trainable parameters: {{trainable_params:,}}")'
    ))

    # ===================== Ph3: Training Config =====================
    cells.append(_md_cell("## Phase 3: Training Configuration\n\n"
        "Each hyperparameter below is annotated with its source and confidence."))

    lr = config_vals.get("learning_rate", 2e-5)
    bs = config_vals.get("batch_size", 32)
    epochs = config_vals.get("epochs", 3)
    wd = config_vals.get("weight_decay", 0.01)
    warmup = config_vals.get("warmup_ratio", 0.06)
    scheduler_type = config_vals.get("scheduler", "linear")
    gc = config_vals.get("gradient_clipping", 1.0)
    seed = config_vals.get("seed", 42)

    # Build annotated comments
    annotations = _build_annotations(validated_config)

    cells.append(_code_cell(
        f'# Phase 3: Training Configuration\n'
        f'from transformers import TrainingArguments\n\n'
        f'training_args = TrainingArguments(\n'
        f'    output_dir="./results",\n'
        f'    \n'
        f'    # === Core Hyperparameters ===\n'
        f'    learning_rate={lr},  {annotations.get("learning_rate", "")}\n'
        f'    per_device_train_batch_size={bs},  {annotations.get("batch_size", "")}\n'
        f'    num_train_epochs={epochs},  {annotations.get("epochs", "")}\n'
        f'    \n'
        f'    # === Regularization ===\n'
        f'    weight_decay={wd},  {annotations.get("weight_decay", "")}\n'
        f'    max_grad_norm={gc},  {annotations.get("gradient_clipping", "")}\n'
        f'    \n'
        f'    # === Scheduling ===\n'
        f'    warmup_ratio={warmup},  {annotations.get("warmup_ratio", "")}\n'
        f'    lr_scheduler_type="{scheduler_type}",  {annotations.get("scheduler", "")}\n'
        f'    \n'
        f'    # === General ===\n'
        f'    seed={seed},  {annotations.get("seed", "")}\n'
        f'    \n'
        f'    # === Evaluation & Logging ===\n'
        f'    eval_strategy="epoch",\n'
        f'    save_strategy="epoch",\n'
        f'    logging_steps=50,\n'
        f'    load_best_model_at_end=True,\n'
        f'    metric_for_best_model="eval_loss",\n'
        f'    report_to="none",\n'
        f')\n\n'
        f'print("Training arguments configured.")\n'
        f'print(f"  LR: {{training_args.learning_rate}}")\n'
        f'print(f"  Batch: {{training_args.per_device_train_batch_size}}")\n'
        f'print(f"  Epochs: {{training_args.num_train_epochs}}")'
    ))

    # ===================== Ph4: Training Loop =====================
    cells.append(_md_cell("## Phase 4: Training"))
    cells.append(_code_cell(
        f'# Phase 4: Training Loop\n'
        f'from transformers import Trainer\n'
        f'import numpy as np\n'
        f'from sklearn.metrics import accuracy_score, f1_score\n\n'
        f'def compute_metrics(eval_pred):\n'
        f'    logits, labels = eval_pred\n'
        f'    predictions = np.argmax(logits, axis=-1)\n'
        f'    acc = accuracy_score(labels, predictions)\n'
        f'    f1 = f1_score(labels, predictions, average="weighted")\n'
        f'    return {{"accuracy": acc, "f1": f1}}\n\n'
        f'trainer = Trainer(\n'
        f'    model=model,\n'
        f'    args=training_args,\n'
        f'    # train_dataset=tokenized["train"],\n'
        f'    # eval_dataset=tokenized["test"],\n'
        f'    compute_metrics=compute_metrics,\n'
        f')\n\n'
        f'# Uncomment to train:\n'
        f'# trainer.train()\n'
        f'print("Trainer initialized. Uncomment trainer.train() to start training.")'
    ))

    # ===================== Ph5: Evaluation =====================
    cells.append(_md_cell("## Phase 5: Evaluation"))
    cells.append(_code_cell(
        f'# Phase 5: Evaluation\n'
        f'# results = trainer.evaluate()\n'
        f'# print(f"Evaluation results: {{results}}")\n\n'
        f'# Save model\n'
        f'# trainer.save_model("./final_model")\n'
        f'# tokenizer.save_pretrained("./final_model")\n'
        f'# print("Model saved to ./final_model")\n\n'
        f'print("Pipeline ready. Provide your dataset and uncomment training cells.")'
    ))

    # ===================== Evidence Citations =====================
    cells.append(_md_cell(_build_citations(evidence_report)))

    # Build notebook JSON
    notebook = {
        "nbformat": 4,
        "nbformat_minor": 5,
        "metadata": {
            "kernelspec": {
                "display_name": "Python 3",
                "language": "python",
                "name": "python3",
            },
            "language_info": {"name": "python", "version": "3.11.0"},
        },
        "cells": cells,
    }

    output = Path(output_path).resolve()
    output.write_text(json.dumps(notebook, indent=2, ensure_ascii=False), encoding="utf-8")
    return str(output)


# ===================== Helpers =====================

def _md_cell(source: str) -> dict:
    return {
        "cell_type": "markdown",
        "metadata": {},
        "source": source.split("\n"),
    }


def _code_cell(source: str) -> dict:
    return {
        "cell_type": "code",
        "metadata": {},
        "source": source.split("\n"),
        "outputs": [],
        "execution_count": None,
    }


def _build_config_table(config: dict) -> str:
    """Build a markdown table summarizing the config."""
    lines = [
        "## Configuration Summary\n",
        "| Parameter | Value | Source | Confidence |",
        "|---|---|---|---|",
    ]
    for param in [
        "learning_rate", "batch_size", "epochs", "optimizer",
        "max_seq_length", "weight_decay", "warmup_ratio",
        "scheduler", "gradient_clipping", "dropout", "seed",
    ]:
        entry = config.get(param, {})
        if isinstance(entry, dict):
            val = entry.get("value", "—")
            src = entry.get("source", "—")
            conf = entry.get("confidence", "—")
            if isinstance(conf, float):
                emoji = "🟢" if conf >= 0.7 else "🟡" if conf >= 0.3 else "🔴"
                conf = f"{emoji} {conf:.0%}"
        else:
            val, src, conf = entry, "—", "—"
        lines.append(f"| `{param}` | `{val}` | {src} | {conf} |")

    return "\n".join(lines)


def _build_annotations(config: dict) -> dict:
    """Build inline code comments for each HP."""
    annotations = {}
    for param, entry in config.items():
        if not isinstance(entry, dict):
            continue
        src = entry.get("source", "")
        conf = entry.get("confidence", 0)
        if src == "extracted_from_paper":
            annotations[param] = "# ← from your paper (100%)"
        elif src == "inferred_from_corpus":
            n = entry.get("support_count", 0)
            annotations[param] = f"# ← inferred ({conf:.0%} conf, {n} papers)"
        elif src == "bert_default":
            annotations[param] = "# ← BERT default (low/no evidence)"
        elif src == "auto_corrected":
            annotations[param] = "# ← auto-corrected by validator"
    return annotations


def _build_warnings(contradiction_report, validation_result) -> str:
    """Build warnings markdown section."""
    parts = []

    if contradiction_report:
        contras = contradiction_report.get("contradictions", [])
        if contras:
            parts.append("### ⚠️ Evidence Warnings\n")
            for c in contras[:5]:
                parts.append(f"- **{c['param']}**: {c['message']}")

    if validation_result:
        corrections = validation_result.get("corrections", [])
        if corrections:
            parts.append("\n### 🔧 Auto-Corrections\n")
            for c in corrections:
                parts.append(f"- **{c['param']}**: {c['message']}")

    return "\n".join(parts) if parts else ""


def _build_citations(evidence_report: dict) -> str:
    """Build citations section."""
    papers = evidence_report.get("papers", [])
    if not papers:
        return "## 📚 Citations\n\nNo corpus papers were used for inference."

    lines = [
        "## 📚 Evidence Citations\n",
        f"The following {len(papers)} papers contributed to the HP inference:\n",
        "| # | Title | Similarity | R-Score | Source |",
        "|---|---|---|---|---|",
    ]
    for i, p in enumerate(papers[:15], 1):
        title = p.get("title", "Unknown")[:60]
        sim = f"{p.get('similarity', 0):.3f}"
        rs = f"{p.get('rscore', 0):.3f}"
        src = p.get("source", "—")
        lines.append(f"| {i} | {title} | {sim} | {rs} | {src} |")

    return "\n".join(lines)
